### ISSUE TITLE
question: how to transfer the query vector to a binary vector?

### ISSUE THREAD

**Issue by kemingy** [gaoj0017/RaBitQ#3]
Thanks for the idea and code implementation.

The query vector is scaled to u8 and converted to a 4x binary vector. But I don't understand why the transposition is done this way. I didn't find any explanation in the paper or referenced paper (maybe I missed something).

From what I understand, the binary is extracted from the middle of the u8 (after the shift & mask), then each value is added by itself, this process iterates for 4 times to get the 4x binary for each value.

https://github.com/gaoj0017/RaBitQ/blob/528705f6e2914caebc073f1227b070fbda1b3c8c/src/space.h#L82-L95

**Comment by VoVAllen** [comment]
I have similar questions: why it's `_mm256_slli_epi32` to move left instead of move right? For q in 8bit, the quantized bit vector should be q // 2**(8-B_QUERY), therefore the right operation seems move right here

**Comment by gaoj0017** [comment]
The input of this function is a sequence of u8 and the output is 4 compactly stored binary vectors, so this function basically reorganizes the data layout, i.e., it move every bit to the location it should be at. This is only one possible implementation while there could other implementations. 

1. line 83 enumerates the sequence of u8.
2. line 84 loads 32x u8 into a 256-bit AVX2 register. 
3. Note that each variable `q[i]` has 4 non-zero bits and is stored with a u8. This means its first 4 upper bits are zeros. This is the reason that we do line 85. 
4. Then we iteratively extract the first bit of each variable four times. (line 86) `_mm256_movemask_epi8` can exact the first bit of every 8-bit unsigned integer in 256-bit AVX2 registers. (line 87)
5. Note that the order of bits extracted from the above process is reversed, i.e., the 0th dimension is mapped to the 31th bit, so we reverse it back (line 88). 
6. For the exacted binary vector, we put it where it should be (line 89). 
7. We shift the u8 in the AVX2 register by 1 bit (line 90). I don't remember why I write `v = _mm256_add_epi32(v, v)`... It is equivalent to `v = _mm256_slli_epi32(v, 1)`. The shift operation should be easier to understand. 

Since this is not a bottleneck in the algorithm, I did not elaborate much on this function. Possibly there are better implementations which can achieve the same thing.

**Comment by kemingy** [comment]
Thanks for your explanation! I forgot the u8 has 4 upper bits that are still zero.
